### ISSUE TITLE
[zod-nestjs][zod-openapi] use `$ref` instead of `properties` for `items`

### ISSUE THREAD

**Issue by nidomiro** [anatine/zod-plugins#108]
I want to ditch classvalidator for zod in nestjs. Unfortunately my company is strict about the format of the OpenApi-Document.
What my company expects:
```yaml
components:
  schemas:
    MyListResponse:
        myList:
          items:
            $ref: '#/components/schemas/ItemType'
```

what currently is generated:

```yaml
components:
  schemas:
    MyListResponse:
        myList:
          items:
            properties:
              prop1:
                description: Desc. of prop1
                format: decimal
                type: number
```

how is it possible to get the first version when generating the document?
