### ISSUE TITLE
[zod-openapi] property type generated as list is invalid in YAML

### ISSUE THREAD

**Issue by yohny** [anatine/zod-plugins#241]
I have a zod schema defined as:
```ts
export const testSchema = extendApi(
  z.object({
    inventoryNumber: extendApi(z.string().optional(), {
      description: "The inventory number",
      example: "12345",
    }),
  }),
);
```
which results in incorrect OpenApi YAML schma:
```yaml
 TestDto:
      type:
        - object # type can not be list
      properties:
        inventoryNumber:
          type:
            - string # type can not be list
          description: The inventory number
          example: '12345'
```
the problem is the `type` specification - it can not be list, only single values are allowed (see https://swagger.io/docs/specification/v3_0/data-models/data-types/ section `Mixed Types`) so the result should be:
```yaml
 TestDto:
      type: object
      properties:
        inventoryNumber:
          type: string
          description: The inventory number
          example: '12345'
```

I'm generatign the scchema document in NestJs and I have set it up with `patchNestjsSwagger` call as specified [in docs](https://github.com/anatine/zod-plugins/blob/main/packages/zod-nestjs/README.md#set-up-your-app)

zod-apenapi version `2.2.5`
