### ISSUE TITLE
[zod-openapi] nativeEnum on string/number enum behaves unexpected

### ISSUE THREAD

**Issue by spech66** [anatine/zod-plugins#66]
**Description**

I have the following Enum.
```
export enum TestEnum {
    FIRST = 10,
    SECOND = 20,
}
```

Using it in the zodSchema
```
testEnum: z.nativeEnum(TestEnum).default(TestEnum.SECOND),
```

This will generate the following Schema
```
        testEnum:
          type: string
          default: 20
          enum:
            - FIRST
            - SECOND
            - 10
            - 20
```

This is the generated example in Swagger
```
{ "testEnum": "40" }
```

**Errors/Problems**
- Without default the value will be "FIRST" which will also raise an error that only 10/20 is allowed.
- Providing "FIRST", "SECOND" is not allowed.
- Running the example will give an error that only numbers are allowed but value is shown as string.

**References**
The other zod/openapi library seems to have fixed the same error:
https://github.com/asteasolutions/zod-to-openapi/issues/43
