### ISSUE TITLE
[zod-openapi] should not generate empty required

### ISSUE THREAD

**Issue by OlivierCuyp** [anatine/zod-plugins#86]
Hi,

I'm using `zod-openapi` and [express-openapi-validator](https://www.npmjs.com/package/express-openapi-validator).
Seems to work well except when all properties of an object are optional.
Then I got this error:

```
Structural error at components.schemas.Meta.required
should NOT have fewer than 1 items
limit: 1
```

Generated schema is:

```
    Meta:
      type: object
      properties:
        total:
          type: integer
          maximum: 0
        offset:
          type: integer
        limit:
          type: integer
      required: []
```

If nothing is required, the required field shouldn't be present by OpenApi 3.0 specification.
[Swagger Editor](https://editor.swagger.io/) will raise the same error.
